### ISSUE TITLE
Examine source of large error bars in 0.10.0 release

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#1041]
The [benchmark data for 0.10.0](https://github.com/choderalab/perses/releases/tag/0.10.0) has a few compounds with very large error bars.

![image](https://user-images.githubusercontent.com/3656088/173436774-b950ca79-7dcc-44e3-8e89-8740638b5804.png)

We should take a look at these and see if there is something weird with the atom mappings, or other discernible issue.

**Comment by zhang-ivy** [comment]
I've gone through the release notes and tried to pick out potential reasons why the error has increased for some mutations:
- Bug generated by changes upstream in the openmm package -- default method for calculating solvent padding changed, which resulted in smaller boxes. Fixed by adding more padding to the simulation box, it is now 1.1 nm. Openmm issue https://github.com/openmm/openmm/issues/3502. Perses issue https://github.com/choderalab/perses/issues/949 (https://github.com/choderalab/perses/pull/953)
- Use names (instead of indices) for fetching the force components of a system, avoiding issues with force reordering upstream in openmm. Issue https://github.com/choderalab/perses/issues/993 (https://github.com/choderalab/perses/pull/976 and https://github.com/choderalab/perses/pull/1007)
- Use of unique names for force components in HybridTopologyFactory (https://github.com/choderalab/perses/pull/1022).
- Introduce unsampled_endstates boolean option in input YAML file, which enables/disables creation of unsampled endstates with long-range sterics correction. Issue https://github.com/choderalab/perses/issues/1033 (https://github.com/choderalab/perses/pull/1037).

**Comment by zhang-ivy** [comment]
Ah great find! Could you point me to the code you're using to compute the free energies (and errors) for the above plots? 

And also could you retrieve the `.nc` files for one transformation (both phases, with and without unsampled endstates)? We may need take a closer look at how the free energies (and errors) are computed.

**Comment by zhang-ivy** [comment]
LInk to the code used for computing free energies: https://github.com/choderalab/perses/blob/main/perses/analysis/load_simulations.py
