### ISSUE TITLE
CUDA platform hardcoded in geometry engine

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/perses#1085]
When playing with different tests and platforms I realized that perses currently *requires* a CUDA platform to work. Specifically,  `FFAllAngleGeometryEngine._log_propose` method has the platform hardcoded in https://github.com/choderalab/perses/blob/87bc1d00c6c087b0dc13b38f83f5e2c4d13e012d/perses/rjmc/geometry.py#L453

My guess is that this is a bug and we actually want to allow different platforms to be used in this case. Uless there's a real reason why CUDA is required for this method.

**Comment by jchodera** [comment]
We should be using the `CPU` or `Reference` platforms for geometry things!
We should also make sure the OpenMM `Context` is explicitly `del`eted / cleaned up.

**Comment by ijpulidos** [comment]
> We should be using the `CPU` or `Reference` platforms for geometry things! We should also make sure the OpenMM `Context` is explicitly `del`eted / cleaned up.

I think I'm fine with using `CPU` or `Reference` for the geometry engine. I just wonder if there's a case where it is advisable to use the GPU for this purpose, from the top of my head, maybe for big[huge?] systems.

**Comment by ijpulidos** [comment]
I'm glad I pointed to this. Just tested and by avoiding using the `CUDA` platform in the geometry engine we also solve the slowdown problem mentioned in https://github.com/choderalab/perses/issues/1058#issuecomment-1218632972 !!

I will be proposing the changes in a PR in a few mins.

**Comment by jchodera** [comment]
This would depend on whether or not sterics are used in the geometry engine.
By default, I believe we use just valence terms, where CPU/Reference should be fastest.
We may want to use (and subsequently clean up) the fastest Platform if the sterics option is used.

Out of curiosity, is the issue here that we just didn't explicitly clean up the `Context` objects after the geometry engine calls exited? If so, this would have tied up resources on the GPU.

**Comment by ijpulidos** [comment]
> This would depend on whether or not sterics are used in the geometry engine. By default, I believe we use just valence terms, where CPU/Reference should be fastest. We may want to use (and subsequently clean up) the fastest Platform if the sterics option is used.

I checked the code and all the calls to `FFAllAngleGeometryEngine` are using `use_sterics=False` (which is also the default value) :+1: 

> 
> Out of curiosity, is the issue here that we just didn't explicitly clean up the `Context` objects after the geometry engine calls exited? If so, this would have tied up resources on the GPU.

This might be what was triggering the issue originally. Even though, judging from GPU usage, I can see memory being allocated when the geometry engine runs and deallocated after it finishes doing its thing. That's of course just a qualitative check. How would one clean the `Context` explicitly?

**Comment by jchodera** [comment]
After we create a `Context` with something like
```python
context = openmm.Context(system, integrator, platform)
```
we should be sure to explicitly `del context` to ensure those GPU resources are freed:
```python
del context
```
Otherwise, Python may not garbage collect it until much later.

It will be important to carefully comb through [geometry.py](https://github.com/choderalab/perses/blob/6aedcd0e1fa91e7039b4482db37def1bc20bf55c/perses/rjmc/geometry.py) and make sure any `Context` we create is also cleaned up this way before returning.

**Comment by jchodera** [comment]
For example, in [`_logp_propose`](https://github.com/choderalab/perses/blob/6aedcd0e1fa91e7039b4482db37def1bc20bf55c/perses/rjmc/geometry.py#L328-L705), I count that we create _three_ `Context` objects but only clean up one of them.

**Comment by zhang-ivy** [comment]
Ah I see that three contexts are being created in `_logp_propose`, and all three of them are being cleaned up here: https://github.com/choderalab/perses/blob/6aedcd0e1fa91e7039b4482db37def1bc20bf55c/perses/rjmc/geometry.py#L693

There is another context created in [`_corrected_reduced_potential`](https://github.com/choderalab/perses/blob/6aedcd0e1fa91e7039b4482db37def1bc20bf55c/perses/rjmc/geometry.py#L707-L736) that is never deleted, so I wonder if this is what's causing the slowdown
