### ISSUE TITLE
geometry_engine should be an optional argument

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#230]
A new required argument `geometry_engine` was recently added to [`ExpandedEnsemblerSampler`](https://github.com/choderalab/perses/blob/master/perses/samplers/samplers.py#L735), breaking the existing API and doctests and making it so other scripts (like the [selectivity example](https://github.com/choderalab/perses/tree/master/examples/abl-src-selectivity)) no longer work.

@pgrinaway: Is there a reason that we can't just have a sensible default for the geometry engine, and make `geometry_engine` optional?

**Comment by jchodera** [comment]
For example, we could have `geometry_engine=None` and include
```python
if geometry_engine is None:
   geometry_engine = geometry.FFAllAngleGeometryEngine() 
```

**Comment by pgrinaway** [comment]
We could do this.

**Comment by pgrinaway** [comment]
Ok, so I realize this issue is from a while ago. It seems now that the test systems and such have been updated to reflect the new API. It seems more sensible to just update the selectivity example to use the new API, rather than updating the signature to have `geometry_engine` as a keyword argument then having to update the rest of the classes. I'm happy to update the selectivity example.

**Comment by jchodera** [comment]
I'm not sure I follow. If we simply change
```python
    def __init__(self, sampler, topology, state_key, proposal_engine, geometry_engine, log_weights=None, scheme='ncmc-geometry-ncmc', options=None, platform=None, envname=None, storage=None):
 ```
to
```
    def __init__(self, sampler, topology, state_key, proposal_engine, geometry_engine=None, log_weights=None, scheme='ncmc-geometry-ncmc', options=None, platform=None, envname=None, storage=None):
...
if geometry_engine is None:
   geometry_engine = geometry.FFAllAngleGeometryEngine() 
 ```
doesn't that make *everything* just work, without the need to update *any* examples?

**Comment by pgrinaway** [comment]
>doesn't that make everything just work, without the need to update any examples?

Well, either we have to change the core API, or we have to change the example. So something is going to need to be updated. And if we decided to take your suggestion, I'd either have to update all the testsystems to have `geometry_engine` as a keyword argument, or leave them as-is and pass `geometry_engine` as a positional argument to a keyword. _Technically_, this works, but it doesn't seem very clean. I suggested what I did because I think it involves fewer changes.

**Comment by jchodera** [comment]
Ah, I see. So the only concern is in specifying an optional argument as a positional argument will work, but is untidy?

**Comment by pgrinaway** [comment]
Yeah. Especially as we're trying to get everything up to speed re: cleanliness and testing.

**Comment by pgrinaway** [comment]
I think this is no longer an issue
