### ISSUE TITLE
Test infrastructure

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#248]
This is low priority (for me--anyone else speak up if it's critical), but I think there are a couple issues with the current testing infrastructure on travis:
- It's fundamentally limited to a subset of the tests due to the lack of GPU and sufficient build time
  - I realize Jenkins is supposed to remedy this--perhaps I should take a closer look. But if there are other solutions that are less complicated, that would be great.
- It takes a lot of time, which means that other projects are often starved of travis time. I don't think this has reached critical levels yet, but reducing the amount of travis allocation that we take could be nice.

I've opened this issue to brainstorm potential solutions to these issues and their importance.

**Comment by jchodera** [comment]
We have a [test framework on Jenkins](https://jenkins.choderalab.org/job/test-perses-linux-xeon-gtxtitan-src/) for perses that uses `src`, but since the dev boxes have moved, the firewall ports are no longer open between Jenkins and `src`. I've asked to get that fixed.

Are there cloud services where we can test the slow GPU stuff?

Also, maybe we can pare down what is being tested on travis?

**Comment by pgrinaway** [comment]
>Are there cloud services where we can test the slow GPU stuff?

I'll look into this.

>Also, maybe we can pare down what is being tested on travis?

Possibly. I don't think it's urgent, but I want to make sure our alternative is working before paring down anything on travis.

**Comment by jchodera** [comment]
Do we know what the slow bits are?

If the simulations are slow on travis, an alternative might be to set up
some tiny systems for travis:
* Host-guest system for sampling over ligands
* Tiny peptide for sampling over protein

**Comment by pgrinaway** [comment]
Good question. I'll have to look into which parts are slow.

**Comment by pgrinaway** [comment]
@jchodera I've changed the label on this issue because I think we are running into some problems with testing that you have brought up:

* Tests only run on a subset of the code, since we can't afford to run much without a GPU, and made even lighter because we destroy the rest of the lab's ability to use travis

* There's often a pretty long delay in running tests, probably due to some throttling by travis. 

* Efficiency benchmarks can't be easily automated since we can't run any real systems on travis.

* Jenkins meets with resistance at MSK

(feel free to add to the list)

As I said in another thread, I don't think there are any ready-made CI solutions using GPUs, unfortunately. @jchodera suggested what is probably our best bet, running Jenkins on EC2. I think this would be good to try, we just need to work out:

* How often should tests run (billing concerns)?

* How will we pay for the instance time and storage?
    * Personal account
    * Institutional account
    * Some kind of grant from Amazon?

* Other cloud services (I'm less familiar, but no sense in not mentioning)
    * Azure
    * Google

I'm thinking maybe we should get the ball rolling on this sooner rather than later, but I could be wrong.

**Comment by jchodera** [comment]
Here's my current suggestion:
* Spin up a [Jenkins](https://jenkins.io/) instance on some cloud provider. We can use, for example, the [Bitnami Jenkins stack](https://bitnami.com/stack/jenkins).
* Use the [Blue Ocean Jenkins plugin](https://jenkins.io/projects/blueocean/) to avoid losing our minds.
* Use the [EC2 SpotFleet Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Amazon+EC2+Fleet+Plugin) to spin up [P2](https://aws.amazon.com/ec2/instance-types/?sc_channel=PS&sc_campaign=acquisition_US&sc_publisher=google&sc_medium=ec2_b&sc_content=sitelink&sc_detail=ec2&sc_category=ec2&sc_segment=instance_types&sc_matchtype=p&sc_country=US&s_kwcid=AL!4422!3!154833506536!p!!g!!ec2&ef_id=Vg2lZgAAAa5t7xKi:20161220190820:s) spot instances (K80 equivalents), or the [Kubernetes plugin](https://cloud.google.com/solutions/jenkins-on-container-engine) [Google Compute GPU instances](https://cloud.google.com/gpu/) (Pascal GPU instances)

Does this sound reasonable? Would you prefer EC2 or Google Compute Engine?

**Comment by jchodera** [comment]
[This blog post](https://www.davemaple.com/articles/install-jenkins-on-amazon-linux/) suggests running Jenkins on a [T2.medium EC2 instance](https://aws.amazon.com/ec2/instance-types/), which currently costs [$26.28/month](https://aws.amazon.com/ec2/pricing/reserved-instances/pricing/?refid=em_26483).

**Comment by pgrinaway** [comment]
I like your suggestion. That looks like the most straightforward way to design things at the moment, and will accomplish what we want. I do want to take a close look at some of the AWS CI tools (which might simplify some of the automation further), just in case. 

>Would you prefer EC2 or Google Compute Engine?

I'm fine with any cloud platform, but my preference is usually Amazon because

* I'm most familiar with it by far.

* It has a pretty extensive set of automation tools (Google and Azure might as well, but I am not so familiar)

**Comment by jchodera** [comment]
[`travis-build`](https://github.com/travis-ci/travis-build), the tool that travis-ci workers use to convert the `.travis.yml` into build scripts, might come in handy here.

**Comment by jchodera** [comment]
As an alternative to building a whole Jenkins infrastructure, I wonder if we can simply use the [travis-ci S3 deploy](https://docs.travis-ci.com/user/deployment/s3/) to push the built conda package and then using the [ECS CLI](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html) to launch a docker image and run a script to install the conda package, run the nosetests, and report the results. It looks like [ECS can use GPUs](https://aws.amazon.com/blogs/compute/orchestrating-gpu-accelerated-workloads-on-amazon-ecs/).

The one major downside is that it doesn't appear to be easy to suck the output of the nosetests into the travis logfile because ECS doesn't yet support interactive TTYs on docker tasks it launches. There is [a workaround](https://github.com/aws/amazon-ecs-agent/issues/462#issuecomment-236987950), though.

This scheme might be much less complex than the Jenkins route, since it would allow us to easily build off of the current infrastructure and go just a bit further to run the tests on AWS after things build correctly.
