### ISSUE TITLE
RDKit support

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#342]
SiliconTx says that RDKit support is high priority.

**Comment by pgrinaway** [comment]
Changed to low priority now that we can use OpenEye.

**Comment by pgrinaway** [comment]
Since the call indicated that this was relatively high priority, I am going to outline briefly how OpenEye is currently used and how it might be replaced:

# Reversible Jump steps

## ProposalEngines

* First, we propose a molecule given our set of molecules. This uses OpenEye to:
    * [Make a map](https://github.com/choderalab/perses/blob/master/perses/rjmc/topology_proposal.py#L1545) (with MCSS) between the current molecule and the other molecules
    * [Convert](https://github.com/choderalab/perses/blob/master/perses/rjmc/topology_proposal.py#L1416) from an OpenMM topology residue to SMILES
    * [Convert](https://github.com/choderalab/perses/blob/master/perses/rjmc/topology_proposal.py#L1509) from an OEMol to an OpenMM topology residue

 * I'll update this with how we use OpenEye in the polymer `ProposalEngines`, but I believe it is just for atom mapping.

## SystemGenerator

* This uses the [openmoltools forcefield generators](https://github.com/choderalab/openmoltools/blob/master/openmoltools/forcefield_generators.py) to parameterize the system that is being proposed. 
    * Convert an OEMol into an OpenMM Topology
    * Use antechamber + AM1-BCC (OpenEye quacpac) for charges

## GeometryEngine

* [Convert](https://github.com/choderalab/perses/blob/master/perses/rjmc/geometry.py#L358) OpenMM residue to OEMol
* Use OEMol to identify rigid bonds
    * [Add an extra torsion term](https://github.com/choderalab/perses/blob/master/perses/rjmc/geometry.py#L1506) based on reference conformer from Omega (this helps with ring closure, bond stereochem)
 * Use OEMol to identify angles for aromatic heavy atoms
    * [Add an extra angle term](https://github.com/choderalab/perses/blob/master/perses/rjmc/geometry.py#L1618) for these to further aid ring closure.

## Miscellaneous

* Molecule I/O in testsystems

# [Nonequilibrium setup](https://github.com/choderalab/perses/blob/master/perses/dispersed/relative_setup.py)

In general, the nonequilibrium setup uses the parts from RJMC, so resolving those will resolve the nonequilibrium setup stuff. I've tried to include links to roughly where we're using the OpenEye toolkits to perform those actions, so I hope that helps. If there are any questions please feel free to ask.

Also, a sincere thanks to Silicon Therapeutics for pushing this forward. I think it's an important step in making sure Perses is actually an open source project and usable by everyone.

@brycestx I don't think I can tag Marcell here, so if you want to go for it.

**Comment by davidlmobley** [comment]
Just saw this as Patrick posted on Slack.

It seems like the `Topology` object (which is effectively a molecular container) being planned for `openforcefield` could also be something which could make it much easier to replace dependence on OpenEye/RDKit in particular not just in the `openforcefield` initiative but elsewhere in our ecosystem.

Silicon mentioned this to me in a recent call as well and I pointed out a need for a open source AM1-BCC scheme (or other comparable method) outside of antechamber.

**Comment by jchodera** [comment]
This will be handled by #747
