### ISSUE TITLE
Accelerate hybrid exception handling

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#358]
Hybrid system construction is slow due to nested for loops. These should be replaced with set operations.

**Comment by pgrinaway** [comment]
Current status of this:

* I've fixed the issue with the faster version of hybrid exception handling. It's down from around 300s to less than 2s.

* Current slowness is from `getExceptionParameters`

**Comment by jchodera** [comment]
Is it the [actual call to `System.getExceptionParameters()`](https://github.com/choderalab/perses/blob/f2a6eafd5e87dbc793192943048ddf5187d3e472/perses/annihilation/new_relative.py#L1272) that is slow---presumably cumulatively over many calls? Or is it the [whole exception-handling block](https://github.com/choderalab/perses/blob/f2a6eafd5e87dbc793192943048ddf5187d3e472/perses/annihilation/new_relative.py#L1269-L1346)?

If it really is just `System.getExceptionParameters()`, we have several options:
* Move to a scheme where one `System` or `Force` is duplicated with `deepcopy`, where you'd only have to retrieve exceptions from atoms that change in the second system. You may need additional information passed to the factory about which atoms are the "same" and which atoms are part of the "alchemical" region in which exceptions may change
* See if we can have OpenMM add a way to access parameters that are not unit-wrapped. For example maybe swig could add hidden methods like `_getExceptionParameters()` that would return the non-swig-wrapped results.

**Comment by jchodera** [comment]
One thing I noticed is that inside a loop over exceptions in the old system, you call [`self._find_exceptions`](https://github.com/choderalab/perses/blob/f2a6eafd5e87dbc793192943048ddf5187d3e472/perses/annihilation/new_relative.py#L1305), which also makes a loop over most of the exceptions in the new system. I bet building exception `dict`s once for old and new `System` objects would be a much faster way to handle this instead of looping through both lists each time.

**Comment by pgrinaway** [comment]
Good point! Thanks!

**Comment by pgrinaway** [comment]
Addressed
