### ISSUE TITLE
Add tests for hybrid alchemical factory

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#365]
Due to its complexity, we need a good set of tests for the hybrid alchemical factory in order to guarantee correctness.

**Comment by jchodera** [comment]
From what I recall of our earlier discussions, the best thing to do was simply to ensure we have good *overlap* with both initial and final states, since this is all we really need for a successful calculation. 

The test is simple:
* For each of the nonbonded methods we want to support (focusing on PME in TIP3P explicit solvent first), generate systems A and B containing, say, two different guest molecules in a macromolecular host.
* Generate a hybrid alchemical system from A and B.
* Set `lambda = 0` and run an equilibrium simulation of the hybrid system. Compute the overlap of the hybrid system with the real system A.
* Set `lambda = 1` and run an equilibrium simulation of the hybrid system. Compute the overlap of the hybrid system with the real system B.

While the unique atoms that become dummy atoms at `lambda = 0` or `lambda = 1` will reduce the overlap somewhat, we should still be able to obtain useful overlap with the fully interacting states since we will have to include end point perturbations to the fully interacting states to recover the full PME energetics.

This test should be sufficient for our purposes, and hopefully easy to implement!

**Comment by pgrinaway** [comment]
These tests have been added in a number of PRs.
