### ISSUE TITLE
Change endstate validation test to use GPU in double precision mode

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#657]
We should update the endstate validation tests to use the GPU platform in double precision mode.

Let's see if we can fall back gracefully to Reference if the GPU is not available.

**Comment by jchodera** [comment]
What we really want is the fastest double precision platform.

**Comment by hannahbrucemacdonald** [comment]
This is technically fixed, as we now run the test on `CUDA` with double, if it's available, otherwise fall back to the slower but still correct `Reference`. Fixed in #659

I have opened an openmm issue https://github.com/openmm/openmm/issues/2635
to see if there's a nicer way we could do this (i.e. potentially capturing OpenCL platform if double is possible.)

I am going to close this, and open another issue #663
