### ISSUE TITLE
Reaction Field not working

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#661]
I added the `nonbonded_method` keyword to allow for reaction field to be run, but this doesn't seem to work, as the simulation still ends up running with PME. Not sure what's going wrong, but maybe something is getting overwritten during the hybrid system generation?

I will take some time to debug in the next few days

**Comment by hannahbrucemacdonald** [comment]
@jchodera 


I'm not sure what the behaviour of this _should_ be

https://github.com/openmm/openmmforcefields/blob/11a9ed2edf0745e77d3e362f27a6c1d5b77abfc5/openmmforcefields/generators/system_generators.py#L80


but we were passing in forcefield_kwargs = {'nonbondedmethod' : app.CutoffPeriodic}

but then it's overwritten by the default for `periodic_forcefield_kwargs` which is PME.

Is it that we are doing it wrong? Or should the default behaviour of SystemGenerator be to first check if nonbondedmethod is defined in one of the other dictionaries?

**Comment by jchodera** [comment]
Good catch!

In order to figure out how to apply parameters to both periodic and non-periodic systems, I wanted to make sure that these were specified in `nonperiodic_forcefield_kwargs` and `periodic_forcefield_kwargs`. 

How about this: We could throw an exception if someone specifies a `nonbondedMethod` in `forcefield_kwargs` instead of `periodic_forcefield_args` or `nonperiodic_forcefield_args`? We can make it informative to instruct the user that this should be put into one of those two.

The fix for perses should be easy then---just change
```python
 forcefield_kwargs = {'removeCMMotion': False, 'ewaldErrorTolerance': self._pme_tol, 'nonbondedMethod': self._nonbonded_method,'constraints' : app.HBonds, 'hydrogenMass' : self._hmass} 
```
to
```python
forcefield_kwargs = {'removeCMMotion': False, 'ewaldErrorTolerance': self._pme_tol, 'constraints' : app.HBonds, 'hydrogenMass' : self._hmass} 
periodic_forcefield_kwargs = {'nonbondedMethod': self._nonbonded_method} 
```
and feed both to `SystemGenerator`.

**Comment by hannahbrucemacdonald** [comment]
Ok sounds good, that's the change I've made in perses. Should I open an openmmforcefields issue? Would you like me to make the fix, or do you want to?

**Comment by jchodera** [comment]
I've already opened an issue here and am just about to push a fix:
https://github.com/openmm/openmmforcefields/issues/108
