### ISSUE TITLE
Unsampled endstate correction for reaction field sims??

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#666]
Ok so running Bace with PME and RF there's clearly something wrong with RF.
**RF in title means reaction field, no RF means default (i.e. PME)**

![image](https://user-images.githubusercontent.com/43652597/78991458-e3e05d00-7b30-11ea-9fc4-094cb269418a.png)
![image](https://user-images.githubusercontent.com/43652597/78991467-e9d63e00-7b30-11ea-8df9-2584d1999d14.png)

If I get rid of the results from the unsampled endstates:

![image](https://user-images.githubusercontent.com/43652597/78991542-12f6ce80-7b31-11ea-9ad7-9b56c2125b55.png)
![image](https://user-images.githubusercontent.com/43652597/78991561-1ee29080-7b31-11ea-97db-b15085184fe4.png)

It's made the PME results slightly worse, and makes the RF results slightly more reasonable again. What exactly should the endstates look like for RF?
    1. move all alchemical atom LJ parameters from CustomNonbondedForce to NonbondedForce
    2. delete the CustomNonbondedForce
    3. set the longest possible cutoff?

**Comment by hannahbrucemacdonald** [comment]
* two simulations finished for RF that haven't finished yet for PME, hence the different number of N, but just sending these to demonstrate
* yes the statistics don't sit within the CI's, this is something David Hahn has fixed but I haven't integrated the changes yet, but will do now

**Comment by jchodera** [comment]
This is awesome!

Questions: 
* Is Bace the best system to address the question right now? How well does the initial Bace PME result compare with previously reported results by others?
* Should we use AMBER GAFF1 or 2 for this comparison so we can have a better idea of what we expect from other results (e.g. the AMBER-TI study with PME or the Cresset study with RF)?
* Do we have any idea as to how good the sampling or convergence is for those outliers? The efficiency of the protocols could be very different for RF and PME.

For true "correct" RF endstates, the problem is that just enlarging the RF cutoff gives basically zero overlap between, say, 9.0A and 10.0A. We believe this is due to some weirdness in terms of both (1) the offset that OpenMM applies, and (2) the use of atom-based cutoffs rather than group-based cutoffs. So we can't enlarge the RF cutoff---we'd have to just enlarge the NonbondedForce cutoff for LJ computation only.

**Comment by hannahbrucemacdonald** [comment]
> Is Bace the best system to address the question right now? How well does the initial Bace PME result compare with previously reported results by others?

I can look at this, but I don't really mind which system we use for testing. It just has quite a few edges and some reasonably sized transformations. I can also run Thrombin, but that's almost too good --- the correlation is so good it's hard to move forward?

> Should we use AMBER GAFF1 or 2 for this comparison so we can have a better idea of what we expect from other results (e.g. the AMBER-TI study with PME or the Cresset study with RF)?
I'm running gaff2 too, but I was just sending the data necessary to highlight the RF endstate issue I had found, rather than sharing of data

> Do we have any idea as to how good the sampling or convergence is for those outliers? The efficiency of the protocols could be very different for RF and PME.
I can generate some convergence plots for this. This was just to show the endstate data.
