### ISSUE TITLE
Platform force discrepancies

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#670]
On FAH the forces calculated on the CPU don't match those stored in the `state.xml`, which should have been generated using CUDA platform.

What I understand from @jchodera is that the FAH core checks the RMSE between the stored and CPU computed forces, in natural openmm units, divided by the number of atoms and checks if this is bigger than 5.

I can also check the force norm to see if that's high. (high is > 10 kJ/nm)

**Comment by jchodera** [comment]
The platforms only start to significantly agree >10 kJ/nm if the force norm is > 1e6 kJ/nm, but it's good to check to see if we successfully minimized the conformations too.

The big question here is trying to isolate the cause between
1. Something critical in the current `Context` isn't being stored/restored in `Context.getState()/setState()`
2. Something critical in the `State` isn't being stored/restored via `XmlSerializer.serialize/deserialize`
3. Something is actually between `CPU`, `OpenCL`, or `CUDA` implementations when you take the same `State` and create different `Context` objects on these platforms.

This is the easiest thing for me to quickly chase down if you can *provide an example transformation that shows this issue*

**Comment by jchodera** [comment]
To debug one specific case, I can modify `submit-ligpairs.sh` to just run
```bash
#BSUB -J “throm[4]”
```

**Comment by hannahbrucemacdonald** [comment]
I started a script here `/data/chodera/brucemah/PersesAtFoldingAtHome/test_forces.py` but this is doing a % difference check, rather than RMSE. Would it help if I changed this now to mirror the RMSE code?

**Comment by jchodera** [comment]
Yes!

**Comment by jchodera** [comment]
@hannahbrucemacdonald : Instead of a separate script, let's just pull these functions into your `fah_generator.py` script. Our goal is to implement that force discrepancy check and run it to test all three cases above:
https://github.com/choderalab/perses/issues/670#issuecomment-626884144

We can have an optional flag in the YAML enable these tests to run.

It would be easier for me to take this up than some of the other items, so just let me know if you want to hand this off to me.

**Comment by hannahbrucemacdonald** [comment]
Ok If you take this I will keep working on the analysis script and also the `CUDA_ERROR_ILLEGAL_ADDRESS` issue?

**Comment by jchodera** [comment]
Sounds good!

**Comment by jchodera** [comment]
This was due to [this issue](https://github.com/choderalab/perses/pull/667/files#r423482100), where the precision was not explicitly set to `mixed` and `DeterministicForces` was not set for CUDA.

@hannahbrucemacdonald : It looks like you resolved the conversation but neglected to push your changes. Can you do that and then close this issue?

**Comment by hannahbrucemacdonald** [comment]
I think this is closed
