### ISSUE TITLE
CLI script frozen if ligand file not found

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/perses#836]
When trying to get some of the examples running, specifically the one under `SamplerExample` directory I encountered it was stuck. Apparently the `setup_relative_calculation.py` script completely freezes when it cannot find the sdf ligand file specified in the YAML (under the `ligand_file` parameter). Not even a CTRL-C works for killing/stopping the process. The output is as shown in https://gist.github.com/ijpulidos/719a3df44aebc6ec6fb23a474004c4df it just stays there forever, nothing is shown to be running when you monitor system activity you just have to manually kill the process. 

I am attaching a minimal package to replicate the issue [no_sdf_stuck.tar.gz](https://github.com/choderalab/perses/files/6934734/no_sdf_stuck.tar.gz). You would run `python /path/to/setup_relative_calculation.py cdk2_repex_1to10.yaml`

**Comment by jchodera** [comment]
Would it be possible to change this warning into a `FileNotFoundException`?
```
2021-08-04 18:27:53,374:(0.00s):relative_setup:Detected .sdf format.  Proceeding...
Warning: Unable to open "non_existing.sdf" for reading molecules.
```
Presumably, it's because [these calls to `createOEMolFromSDF()`](https://github.com/choderalab/perses/blob/master/perses/app/relative_setup.py#L235-L240)---which we want to ditch for the OpenFF `Molecule.from_file(...)` in the future---will hang or fail if the file doesn't exist. The code is [here](https://github.com/choderalab/perses/blob/5d50cbc305145572a495ed629279e6752bd9f46c/perses/utils/openeye.py#L324-L372).
