### ISSUE TITLE
PointMutationExecutor misses definition of forward_htf 

### ISSUE THREAD

**Issue by schallerdavid** [choderalab/perses#865]
Hi all,

I just started playing with Perses 0.9.2 for point mutations. I think I found a bug in the PointMutationExecutor. When running it with the following parameters I get an Error:

command:

```
solvent_delivery = PointMutationExecutor(
    protein_path, 
    '1', # First and only protein chain 
    str(resid), 
    mutate_to,
    ligand_input=ligand_path,
    ionic_strength=0.15*unit.molar,
    small_molecule_forcefields='openff-2.0.0'
)
```

Error:

```
    334             if conduct_endstate_validation and repartitioned_endstate is None:
--> 335                 zero_state_error, one_state_error = validate_endstate_energies(forward_htf._topology_proposal, forward_htf, added_valence_energy, subtracted_valence_energy, beta=beta, ENERGY_THRESHOLD=ENERGY_THRESHOLD)
    336                 if zero_state_error > ENERGY_THRESHOLD:
    337                     _logger.warning(f"Reduced potential difference of the nonalchemical and alchemical Lambda = 0 state is above the threshold ({ENERGY_THRESHOLD}): {zero_state_error}")

NameError: name 'forward_htf' is not defined
```

Looking at the corresponding [file](https://github.com/choderalab/perses/blob/410ca4f82fdfd71fe06edab718f6434e2d38356b/perses/app/relative_point_mutation_setup.py#L335) you can see that 'forward_htf' is not defined.

I tracked it down to this [commit](https://github.com/choderalab/perses/commit/412750c457712da1875c7beabfe88b2838f7f197#diff-b8f1b8770beeae3c016d936d6e8276134c5c92836b2fea2adb739e0a14747234), in which the definition of 'forward_htf' was deleted. 

Interestingly, in your [test](https://github.com/choderalab/perses/blob/410ca4f82fdfd71fe06edab718f6434e2d38356b/perses/tests/test_relative_point_mutation_setup.py#L13) you pass `conduct_endstate_validation=False` to the PointMutationExecutor, which will omit the usage of 'forward_htf'.

We could either add the definition of 'forward_htf' again or remove the code block using 'forward_htf', if this was intended.

Let me know if I can help and make a PR with a fix.

**Comment by zhang-ivy** [comment]
Usually I set `flatten_torsions=True`, and `flatten_exceptions=True` for protein mutations (because I was seeing sampling problems and therefore flattened them so that we could use REST to enhance sampling) and when using these flags, we cannot validate the endstate energies, so I always set `conduct_endstate_validation=False`. 

Additionally, the endstate validation should only happen when generating the vanilla HybridTopologyFactory, not for the RepartitionedHybridTopologyFactory (used for REST), which is why [this line ](https://github.com/choderalab/perses/blob/master/perses/app/relative_point_mutation_setup.py#L334) checks to see if `repartitioned_endstate` is `None`.

However, the way you are generating the htf looks fine for now (better to try without rest first to see if it is needed). 

I think we need a PR with the following changes:
- In [This line](https://github.com/choderalab/perses/blob/master/perses/app/relative_point_mutation_setup.py#L334), `repartioned_endstate is None` should be replaced with `generate_unmodified_hybrid_topology_factory` for clarity.
- We should add a line after the line linked above with something like:
```python
htf = self.get_complex_htf() if is_complex else self.get_apo_htf()
```  
- `forward_htf` in [this line](https://github.com/choderalab/perses/blob/master/perses/app/relative_point_mutation_setup.py#L335) should be changed to `htf`
