### ISSUE TITLE
GPU Tests Failing

### ISSUE THREAD

**Issue by mikemhenry** [choderalab/perses#975]
I need to investigate this further but I thought @zhang-ivy might have an idea on what is going on here:
https://github.com/choderalab/perses/runs/5732242075?check_suite_focus=true

```
        if chain_id not in chain_ids_in_topology:
>           raise Exception(f"Specified chain id {chain_id} not found in the wildtype topology. choices are {chain_ids_in_topology}")
E           Exception: Specified chain id 1 not found in the wildtype topology. choices are ['D', 'D', '3', '4']
```

These tests only run on the GPU, so I'm not surprised that things are working on our GHA CI. We probably should figure out a way to run a short version of these tests on GHA so we can catch them in the PR that causes the regression before we merge them in. 

It looks like https://github.com/choderalab/perses/pull/967 introduced this bug.

**Comment by zhang-ivy** [comment]
@mikemhenry : 
- First, I'd like to point out that these lines can be removed: https://github.com/choderalab/perses/blob/main/perses/tests/test_GPU.py#L48-L51
If the test is only running neq switching on apo barstar, we don't need to include the barnase PDB file as `ligand_input`.
However, I'm not sure that this will fix the error. 
- I can't tell whether the error is coming from generating the htf for the apo phase or the complex phase, but I think the error might be coming from this change: https://github.com/choderalab/perses/pull/967/files#diff-b8f1b8770beeae3c016d936d6e8276134c5c92836b2fea2adb739e0a14747234L186
I made this change because I was getting an error when inputing a solvated PDB and creating the openmm topology from the mdtraj topology, so I thought it would be better to use the openmm topology directly. However, this change may cause differences in the chain IDs, so one thing to try is to change that line to: `protein_topology = protein_md_topology.to_openmm() if solvated else protein_topology`

**Comment by ijpulidos** [comment]
Yes, I think @zhang-ivy is right about the problem being caused by the change in chanIDs when going back and for from/to mdtraj. I'll take a look into this, this might also hint that we need a test for the `PointMutationExecutor` that deals with different chains ids/numbers.

**Comment by zhang-ivy** [comment]
@ijpulidos : Have you had a chance to look into this?

**Comment by ijpulidos** [comment]
> @ijpulidos : Have you had a chance to look into this?

Mot really. Not much other than what I already said up there. As far as I can see, using `mdtraj` ignores/overrides the chain IDs, whereas if we use the `openmm` topology it should use whatever the PDB file specifies as the chain ID.

It is hard to track the consequences of the change that you pointed, but my guess is that we are using `mdtraj`'s topology somewhere where an `openmm`'s one is expected.

**Comment by zhang-ivy** [comment]
>As far as I can see, using mdtraj ignores/overrides the chain IDs, whereas if we use the openmm topology it should use whatever the PDB file specifies as the chain ID.

Yes, that's correct. To be clear, I think I already identified the problem and proposed a solution. I thought you would be able to test my proposed solution out. See [my above comment](https://github.com/choderalab/perses/issues/975#issuecomment-1087612814), particularly:
```
However, this change may cause differences in the chain IDs (since the apo topology will use openmm topology chain ids and the complex topology will use mdtraj-converted openmm chain ids), so one thing to try is to change that line to: protein_topology = protein_md_topology.to_openmm() if solvate else protein_topology
```

**Comment by ijpulidos** [comment]
I was thinking about this and wondering if we just want to change the test code to specify the chain ids. For example use `chain_id = 'C'` [here](https://github.com/choderalab/perses/blob/732dd87e4dfe7e5b5a95b7e304357037798c99b6/perses/tests/test_relative.py#L984), and `chain_id = 'D'` [here](https://github.com/choderalab/perses/blob/732dd87e4dfe7e5b5a95b7e304357037798c99b6/perses/tests/test_relative.py#L989). I tested it locally and it pass the test.

**Comment by zhang-ivy** [comment]
@ijpulidos : I think that would be a band-aid, as it would still mean that there will be a mismatch between the type of topolgies (mdtraj topology vs openmm topology) of `protein_topology` and `complex_topology`. 

Let me summarize the problem:

There are now two ways to load input files for `PointMutationExecutor`:
1. (default) `protein_filename` and `ligand_input` are not solvated. In this case, we will need to combine the protein and ligand topologies to become a `complex_topology` which is done using mdtraj, in these [lines](https://github.com/choderalab/perses/blob/main/perses/app/relative_point_mutation_setup.py#L247-L248). For consistency, this means that we should also make sure that `protein_topology` is created in a similar way, creating an openmm topology from the mdtraj topology (meaning that [this line ](https://github.com/choderalab/perses/pull/967/files#diff-b8f1b8770beeae3c016d936d6e8276134c5c92836b2fea2adb739e0a14747234L186)should not have been removed). 
2. `protein_filename` and `ligand_input` are solvated. In this case, `ligand_input` is the solvated complex. Therefore, we no longer need to combine the protein and ligand topologies. 

We can need to make sure that the protein and complex topologies are consistent within each case, so that means we  have 2 options:
1. For case 1, make `protein_topology` and `complex_topology` openmm topologies that were converted from mdtraj
 and for case 2, leave `protein_topology` and `complex_topology` as openmm topologies (that were not converted from mdtraj)
 2. For both cases, make the topologies openmm topologies that were converted from mdtraj.

**Comment by zhang-ivy** [comment]
@ijpulidos : I think that would be a band-aid, as it would still mean that there will be a mismatch between the type of topolgies (mdtraj topology vs openmm topology) of `protein_topology` and `complex_topology`. 

Let me summarize the problem:

There are now two ways to load input files for `PointMutationExecutor`:
1. (default) `protein_filename` and `ligand_input` are not solvated. In this case, we will need to combine the protein and ligand topologies to become a `complex_topology` which is done using mdtraj, in these [lines](https://github.com/choderalab/perses/blob/main/perses/app/relative_point_mutation_setup.py#L247-L248). For consistency, this means that we should also make sure that `protein_topology` is created in a similar way, creating an openmm topology from the mdtraj topology (meaning that [this line ](https://github.com/choderalab/perses/pull/967/files#diff-b8f1b8770beeae3c016d936d6e8276134c5c92836b2fea2adb739e0a14747234L186)should not have been removed). 
2. `protein_filename` and `ligand_input` are solvated. In this case, `ligand_input` is the solvated complex. Therefore, we no longer need to combine the protein and ligand topologies. 

We can need to make sure that the protein and complex topologies are consistent within each case, so that means we  have 2 options:
1. For case 1, make `protein_topology` and `complex_topology` openmm topologies that were converted from mdtraj
 and for case 2, leave `protein_topology` and `complex_topology` as openmm topologies (that were not converted from mdtraj)
 2. For both cases, make the topologies openmm topologies that were converted from mdtraj.

**Comment by ijpulidos** [comment]
@zhang-ivy I see what you mean, thanks for the explanation, I now get the issue. I think what you suggest should work.

On the other hand. We could also try bookkeeping the chain IDs from the `openmm` topology and use them after we have manipulated the `mdtraj` topologies and converted them to `openmm` ones. This sounds cumbersome and it is better if we can avoid this, but just wanted to mention it just in case we find it useful.

**Comment by jchodera** [comment]
Will the OpenFF `Topology` support for biopolymers help with this?

**Comment by zhang-ivy** [comment]
I think @mikemhenry has addressed this in #985, but not sure if we want to keep this open so that we can find a better long term solution (i.e. use the OpenFF topology)?

Can the OpenFF Topology handle merging two topologies? That's the only reason why mdtraj is currently needed.

**Comment by ijpulidos** [comment]
> Can the OpenFF Topology handle merging two topologies? That's the only reason why mdtraj is currently needed.

I was playing with this today, and I could get a complex topology using the OpenFF `toolkit` and the new `Interchange` object/package. But as far as I know this is till very early and they claim that the way they are joining them is unstable and could cease to exist, hopefully they manage to make it stable and then I guess it can be used for the purpose of this PR in perses.

**Comment by jchodera** [comment]
Do we strictly need a hybrid topology object, or can we create a new kind of object that has two real `Topology` objects and the mapping between the real objects and the hybrid system? 

Can we list all the operations we need to use the "hybrid topology object" for? If so, we can easily design a class that provides all of these operations through a simple API.

**Comment by ijpulidos** [comment]
Related to merging topologies with OpenFF toolkit, they recently added this functionality! https://github.com/openforcefield/openff-toolkit/pull/1194

**Comment by ijpulidos** [comment]
Coming back to the issue of GPU tests failing, I was playing with this and noticed that the fails [here](https://github.com/choderalab/perses/runs/6547307832?check_suite_focus=true#step:9:427) are likely to be due to an upstream issue in OpenMM  version 7.6 (which is what the GPU CI tests seem to be using). I reproduced this locally, it errors locally (with the same error) if I use Openmm76, it works fine if I use Openmm77 (or nightly). Should we just use openmm>7.6 for perses dependencies?

**Comment by mikemhenry** [comment]
I'm fine with that, do we care to look at the root cause on why 7.6 is giving us different energy values?

**Comment by mikemhenry** [comment]
Also we will be testing on 7.7 once this PR gets merged in, which is should shortly 
https://github.com/choderalab/perses/pull/986

**Comment by ijpulidos** [comment]
> I'm fine with that, do we care to look at the root cause on why 7.6 is giving us different energy values?

I vaguely rememeber @jchodera mentioning some errors with specific Openmm versions. I tried to look something between 7.5.1 and 7.7 releases [here](https://github.com/openmm/openmm/issues?page=3&q=is%3Aissue+created%3A%3E2021-04-28+closed%3A%3C2021-11-09), but nothing stood up.

**Comment by mikemhenry** [comment]
GPU tests are passing now https://github.com/choderalab/perses/runs/6577324558?check_suite_focus=true
