### ISSUE TITLE
`validate_endstate_energies_point` failing on openmm nightly

### ISSUE THREAD

**Issue by mikemhenry** [choderalab/perses#993]
`test_PointMutationExecutor_endstate_validation` and a few other tests are failing now on the [nightly tests for openmm](https://github.com/choderalab/perses/runs/6282350509?check_suite_focus=true):

```
             print(f"{components_other[i][0]} -- og: {components_other[i][1]}, hybrid: {components_hybrid[i][1]}")
>           assert np.isclose(components_other[i][1], components_hybrid[i][1])
E           AssertionError

perses/tests/utils.py:964: AssertionError
```

(a few tests are also failing with a force index error, but that is fixed by PR #976 )

**Comment by ijpulidos** [comment]
I was digging into this and I think it is actually the same issue with the ordering of the forces and getting them by index instead of by name. One can see the differences here:
```python
# OMM 7.7

components_other = 
[('HarmonicBondForce', 0.5488766596317677),
 ('HarmonicAngleForce', 0.9512153356249284),
 ('PeriodicTorsionForce', 14.716772049541484),
 ('NonbondedForce', -50.710727641191205),
 ('AndersenThermostat', 0.0)]

# OMM 7.8 Nightly

components_other = 
[('HarmonicBondForce', 0.5879495208741793), 
 ('PeriodicTorsionForce', 14.770935074911064),
 ('NonbondedForce', -50.78580169291506),
 ('HarmonicAngleForce', 0.9146367896110912),
 ('AndersenThermostat', 0.0)]
```
It should be solved by accessing the components by name instead of index. I think the way to go is to use a dictionary in `compute_potential_components` util [here](https://github.com/choderalab/perses/blob/e42fb89e7b7c44a781403449ce273bcc413c787d/perses/tests/utils.py#L326). We then need to adapt the code wherever this function is used.

On a side note, I'm not even sure why `compute_potential_components` is on `test/utils.py` when it's being used as a functional part in the code base outside of the testing.

**Comment by mikemhenry** [comment]
@ijpulidos Check where it is used and move it somewhere else that is more appropriate.
